[package]
name = "tinic_database"
version = "0.1.0"
edition = "2024"
license = "GPL-3"
description = "tinic_database"
repository = "https://github.com/Xsimple1010/Tinic/tree/master/crates/tinic_database"

[dependencies]
sqlite.workspace = true
tinic_generics.workspace = true