[package]
name = "tinic-database"
version = "0.1.0"
edition = "2024"
license = "GPL-3"
description = "tinic-database"
repository = "https://github.com/Xsimple1010/Tinic/tree/master/crates/tinic-database"

[dependencies]
sqlite.workspace = true
tinic-generics.workspace = true
