[package]
name = "tinic-generics"
version = "0.1.0"
edition = "2024"
license = "GPL-3"
description = "tinic-generics"
repository = "https://github.com/Xsimple1010/Tinic/tree/master/crates/tinic-generics"

[dependencies]
libretro-sys.workspace = true
sqlite.workspace = true
