[package]
name = "tinic-ipc-protocol"
version = "0.1.4"
edition = "2024"
license = "GPL-3"
description = "tinic-ipc-protocol"
repository = "https://github.com/Xsimple1010/Tinic/tree/master/crates/tinic-ipc-protocol"


[dependencies]
tinic.workspace = true
serde.workspace = true
